### PR TITLE
New mihomo UI

### PR DESCRIPTION
**Pull request by hunmar**
https://github.com/MetaCubeX/metacubexd

Looks cool

### CODE REVIEW

**Comment by fildunsky** [comment]
Yeah, it's kinda cool but default one was also nice and simple.

# You can install MetaCubeX by just typing

```
cd /opt/clash
wget -O xd.zip https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip
unzip xd.zip
mv metacubexd-gh-pages xd
rm xd.zip
```
Then just change config `external-ui: ./xd`

# Also there are a bit different themed YACD
```
cd /opt/clash
wget -O yacd.zip https://github.com/haishanh/yacd/archive/gh-pages.zip
unzip yacd.zip
mv yacd-gh-pages yacd
rm yacd.zip
```

# And even more simplier GH
```
cd /opt/clash
wget -O gh.zip https://codeload.github.com/cndaqiang/clash-dashboard/zip/refs/heads/gh-pages
unzip gh.zip
mv clash-dashboard-gh-pages gh
rm gh.zip
```

**Comment by hunmar** [comment]
NIce!

I noticed that Metacubexd has the most recent updates among these versions. I completely understand if you choose not to accept this PR, but it would be wonderful if you could include instructions in the README on how to install different versions.

Anyway, thank you for this fantastic product!

**Comment by zerolabnet** [comment]
I know about metacubexd, but my preference is yacd. It's a matter of taste.

**Comment by fildunsky** [comment]
@hunmar Maxim, I've also noticed that ssClash log says that ui exists so not downloading it. That means there is an option to set download url for any chosen ui and the system could download it on its own. Unfortunately it didn't work in my case that's why I've messed with wget, unzip and rename...

There is a nice wiki for Clash and it's mentioned there:

```yaml
external-ui: /path/to/ui/folder
external-ui-name: xd      # Merged into external-ui/xd
external-ui-url: "<https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip>" # Get from GitHub Pages branch
```

I've found these keys but unfortunately somehow it didn't download automatically to my router. Log says downloading and that's it. Maybe there was in issue with root access to create that files, I don't know how to check.

**Comment by fildunsky** [comment]
@hunmar Максим, оказывается достаточно в кофиге Clash поменять `./ui` на `./xd` и перезапустить, Clash сам создаст директорию xd и скачает туда MetaCubeXD

**Pull request closed without merging**
